services:
  - type: web
    name: course-enroller
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: TWILIO_ACCOUNT_SID
        value: your_twilio_sid_here
      - key: TWILIO_AUTH_TOKEN
        value: your_twilio_token_here
    autoDeploy: true
